# Allow additional lines until main driver class can be split
# into smaller classes.

ClassLength:
  Max: 150
AbcSize:
  Max: 20
MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 700
Metrics/LineLength:
  Max: 100
