# Allow additional lines until main driver class can be split
# into smaller classes.

ClassLength:
  Max: 131
AbcSize:
  Max: 20
MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 600
Metrics/LineLength:
  Max: 100
