# Allow additional lines until main driver class can be split
# into smaller classes.

ClassLength:
  Max: 150
AbcSize:
  Max: 20
MethodLength:
  Max: 15
BlockLength:
  Max: 600
TooManyLines:
  Max: 120
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
